In [4]:
import numpy as np
arr=np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
arr1=np.arange(4,20,2)
#array range from 4 to 20 skipping 2 items
arr1

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr1.reshape(4,2)
#create 4x2 array

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [7]:
arr1.reshape(2,4)
#creat 2x4 array

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18]])

In [8]:
arr2=np.arange(5,20)
#array range from 5 to 20
arr2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
arr3=arr2.reshape(3,5)
arr3


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
len(arr2)
#length of array

15

In [10]:
arr2[5:12]

array([10, 11, 12, 13, 14, 15, 16])

In [11]:
arr[5]

5

In [12]:
arr2[5:]
#after 5 th position

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
arr2[:5]
#before 5th position

array([5, 6, 7, 8, 9])

In [16]:
arr2[[1,3,5]]
#multiple position values ..list of list...double brackets

array([ 6,  8, 10])

In [26]:
arr3.dtype

dtype('int64')

In [27]:
arr3

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
arr3[0]
#first row

array([5, 6, 7, 8, 9])

In [31]:
arr3[[0,2]]
#to get the multiple rows

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [34]:
arr3[:,2]
#displays the column of 2 nd position

array([ 7, 12, 17])

In [37]:
arr3[1,:]
#displys the row in the 1st position

array([10, 11, 12, 13, 14])

In [40]:
arr3[2,2]
#item in the positin of[2][2] ie 17

17

In [5]:
arr4=np.arange(10,82,2)
arr4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [45]:
arr4=arr4.reshape(6,6)
arr4

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [13]:
np.linspace(5,16,5)

array([ 5.  ,  7.75, 10.5 , 13.25, 16.  ])

In [46]:
arr4[:,[0,2]]
# all the row items of the colums 0 and 2 ie columns 0, 2

array([[10, 14],
       [22, 26],
       [34, 38],
       [46, 50],
       [58, 62],
       [70, 74]])

In [48]:
arr4[[0,2],:]
#all the colummn elements in rows 0 and 2

array([[10, 12, 14, 16, 18, 20],
       [34, 36, 38, 40, 42, 44]])

In [53]:
arr3

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
np.sum(arr3)

180

In [51]:
arr3.mean()

12.0

In [52]:
np.median(arr3)

12.0

In [54]:
arr3.sum(1)
#sum of row elements

array([35, 60, 85])

In [55]:
arr3.sum(0)
#sum of column ellemnts

array([30, 33, 36, 39, 42])

In [56]:
arr3+5

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr3-5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
arr3*2

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [59]:
arr3/2

array([[2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [61]:
arr3[2]=-4
arr3

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [-4, -4, -4, -4, -4]])

In [65]:
arr3=np.abs(arr3)
arr3

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 4,  4,  4,  4,  4]])

In [66]:
np.sqrt(arr3)

array([[2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [2.        , 2.        , 2.        , 2.        , 2.        ]])

In [67]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
A=np.arange(8).reshape(2,4)
B=np.arange(8).reshape(4,2)
A.dot(B)
#AXB CROSS MUTIPLICATION ROW BY COLUMN

array([[28, 34],
       [76, 98]])

In [7]:
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
A.T
#TRANSVERSE OF THE ARRAY

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])